
# Auth related error codes
AUTH_INVALID_CREDENTIALS = "AUTH_001"
AUTH_EMAIL_EXISTS = "AUTH_002"
AUTH_ACCOUNT_INACTIVE = "AUTH_003"
AUTH_PASSWORD_WEAK = "AUTH_004"
AUTH_INVALID_TOKEN = "AUTH_005"
AUTH_VERIFICATION_REQUIRED = "AUTH_006"

# User related error codes
USER_NOT_FOUND = "USER_001"
USER_INVALID_DATA = "USER_002"
USER_UPDATE_FAILED = "USER_003"

# File related error codes
FILE_TOO_LARGE = "FILE_001"
FILE_INVALID_TYPE = "FILE_002"
FILE_UPLOAD_FAILED = "FILE_003"
FILE_CORRUPT = "FILE_004"
FILE_SAVE_FAILED = "FILE_005"
FILE_EMPTY = "FILE_006"
FILE_UNSAFE_FILENAME = "FILE_007"
FILE_INVALID_RESOLUTION = "FILE_008"

# General validation error
VALIDATION_ERROR = "VALIDATION_001"

# AI Processing errors
PROCESSING_FAILED = "AI_001"
PROCESSING_TIMEOUT = "AI_002"
AI_MODEL_ERROR = "AI_003"
AI_PROCESSING_QUEUE_FULL = "AI_004"
AI_UNSUPPORTED_IMAGE = "AI_005"
AI_LOW_CONFIDENCE = "AI_006"

# Rate limiting errors
RATE_LIMIT_EXCEEDED = "RATE_001"
RATE_LIMIT_REGISTRATION = "RATE_002"
RATE_LIMIT_UPLOAD = "RATE_003"

# Batch operation errors
BATCH_UPLOAD_FAILED = "BATCH_001"
BATCH_PARTIAL_SUCCESS = "BATCH_002"
BATCH_SIZE_EXCEEDED = "BATCH_003"

# Image processing errors
IMAGE_PREPROCESSING_FAILED = "IMG_001"
IMAGE_DUPLICATE_DETECTED = "IMG_002"
IMAGE_METADATA_EXTRACTION_FAILED = "IMG_003"