"""
Error codes cho toàn bộ hệ thống
Quy ước đặt tên: <MODULE>_<DESCRIPTION> = "<MODULE>_<NUMBER>"
"""

# ============================================
# Mã lỗi xác thực (Authentication - AUTH)
# ============================================
AUTH_INVALID_CREDENTIALS = "AUTH_001"
AUTH_EMAIL_EXISTS = "AUTH_002"
AUTH_ACCOUNT_INACTIVE = "AUTH_003"
AUTH_PASSWORD_WEAK = "AUTH_004"
AUTH_INVALID_TOKEN = "AUTH_005"
AUTH_VERIFICATION_REQUIRED = "AUTH_006"
PASSWORD_RESET_ERROR = "AUTH_007"
PASSWORD_CHANGE_ERROR = "AUTH_008"
EMAIL_VERIFICATION_FAILED = "AUTH_009"
INVALID_TOKEN_TYPE = "AUTH_010"
INVALID_TOKEN = "AUTH_011"
USER_NOT_FOUND = "AUTH_012"
INVALID_REFRESH_TOKEN = "AUTH_013"
AUTH_TOKEN_EXPIRED = "AUTH_014"
AUTH_INVALID_VERIFICATION_TOKEN = "AUTH_015"
AUTH_EMAIL_NOT_VERIFIED = "AUTH_016"
AUTH_RESEND_VERIFICATION_LIMIT = "AUTH_017"
AUTH_PASSWORD_RESET_TOKEN_INVALID = "AUTH_018"
AUTH_PASSWORD_RESET_TOKEN_EXPIRED = "AUTH_019"
AUTH_OLD_PASSWORD_INCORRECT = "AUTH_020"
AUTH_SESSION_EXPIRED = "AUTH_021"
AUTH_INVALID_TOKEN_TYPE = "AUTH_022"

# ============================================
# Mã lỗi người dùng (User - USER)
# ============================================
USER_NOT_FOUND = "USER_001"
USER_INVALID_DATA = "USER_002"
USER_UPDATE_FAILED = "USER_003"

# ============================================
# Mã lỗi file (File - FILE)
# ============================================
FILE_TOO_LARGE = "FILE_001"
FILE_INVALID_TYPE = "FILE_002"
FILE_UPLOAD_FAILED = "FILE_003"
FILE_CORRUPT = "FILE_004"
FILE_SAVE_FAILED = "FILE_005"
FILE_EMPTY = "FILE_006"
FILE_UNSAFE_FILENAME = "FILE_007"
FILE_INVALID_RESOLUTION = "FILE_008"

# ============================================
# Mã lỗi xác thực dữ liệu (Validation)
# ============================================
VALIDATION_ERROR = "VALIDATION_001"

# ============================================
# Mã lỗi AI/ML (AI)
# ============================================
PROCESSING_FAILED = "AI_001"
PROCESSING_TIMEOUT = "AI_002"
AI_MODEL_ERROR = "AI_003"
AI_PROCESSING_QUEUE_FULL = "AI_004"
AI_UNSUPPORTED_IMAGE = "AI_005"
AI_LOW_CONFIDENCE = "AI_006"
ANALYSIS_NOT_FOUND = "AI_007"
HEALTH_CHECK_ERROR = "AI_008"
HISTORY_ERROR = "AI_009"
GET_DETAIL_ERROR = "AI_010"
DELETE_ERROR = "AI_011"
AI_ANALYSIS_FAILED = "AI_012"
ANALYSIS_PROCESS_ERROR = "AI_013"
ANALYSIS_ACCESS_DENIED = "AI_014"
GUEST_ACCESS_DENIED = "AI_015"
DELETE_ACCESS_DENIED = "AI_016"
AI_SERVICE_UNAVAILABLE = "AI_017"

# ============================================
# Mã lỗi giới hạn tốc độ (Rate Limit - RATE)
# ============================================
RATE_LIMIT_EXCEEDED = "RATE_001"
RATE_LIMIT_REGISTRATION = "RATE_002"
RATE_LIMIT_UPLOAD = "RATE_003"

# ============================================
# Mã lỗi xử lý hàng loạt (Batch - BATCH)
# ============================================
BATCH_UPLOAD_FAILED = "BATCH_001"
BATCH_PARTIAL_SUCCESS = "BATCH_002"
BATCH_SIZE_EXCEEDED = "BATCH_003"

# ============================================
# Mã lỗi xử lý hình ảnh (Image - IMG)
# ============================================
IMAGE_PREPROCESSING_FAILED = "IMG_001"
IMAGE_DUPLICATE_DETECTED = "IMG_002"
IMAGE_METADATA_EXTRACTION_FAILED = "IMG_003"

# ============================================
# Mã lỗi RBAC (Role-Based Access Control)
# ============================================
ROLE_NOT_FOUND = "RBAC_001"
PERMISSION_NOT_FOUND = "RBAC_002"
ROLE_ASSIGNMENT_FAILED = "RBAC_003"
PERMISSION_DENIED = "RBAC_004"
INSUFFICIENT_PERMISSIONS = "RBAC_005"

# ============================================
# Mã lỗi cơ sở dữ liệu (Database - DB)
# ============================================
DATABASE_CONNECTION_ERROR = "DB_001"
DATABASE_QUERY_ERROR = "DB_002"
DATABASE_TRANSACTION_ERROR = "DB_003"
DATABASE_CONNECTION_TIMEOUT = "DB_004"
DATABASE_LOCK_ERROR = "DB_005"

# ============================================
# Mã lỗi email (Email - EMAIL)
# ============================================
EMAIL_SEND_FAILED = "EMAIL_001"
EMAIL_INVALID_FORMAT = "EMAIL_002"
EMAIL_SMTP_ERROR = "EMAIL_003"
EMAIL_TEMPLATE_ERROR = "EMAIL_004"
EMAIL_RATE_LIMIT_EXCEEDED = "EMAIL_005"

# ============================================
# Mã lỗi First Aid (FIRSTAID)
# ============================================
FIRSTAID_GUIDE_NOT_FOUND = "FIRSTAID_001"
FIRSTAID_INVALID_WOUND_TYPE = "FIRSTAID_002"
FIRSTAID_INVALID_SEVERITY = "FIRSTAID_003"
FIRSTAID_GUIDE_CREATE_FAILED = "FIRSTAID_004"
FIRSTAID_GUIDE_UPDATE_FAILED = "FIRSTAID_005"
FIRSTAID_GUIDE_DELETE_FAILED = "FIRSTAID_006"
FIRSTAID_SEARCH_FAILED = "FIRSTAID_007"
FIRSTAID_STATISTICS_ERROR = "FIRSTAID_008"
FIRSTAID_GUIDE_ERROR = "FIRSTAID_009"
WOUND_TYPES_ERROR = "FIRSTAID_010"
FIRSTAID_SEARCH_ERROR = "FIRSTAID_011"
FIRSTAID_VALIDATION_ERROR = "FIRSTAID_012"
FIRSTAID_GUIDE_NOT_FOUND_ERROR = "FIRSTAID_013"

# ============================================
# Mã lỗi Guest (GUEST)
# ============================================
GUEST_SESSION_NOT_FOUND = "GUEST_001"
GUEST_SESSION_EXPIRED = "GUEST_002"
GUEST_SESSION_CREATE_ERROR = "GUEST_003"
GUEST_SESSION_ERROR = "GUEST_004"
GUEST_UPLOAD_LIMIT_EXCEEDED = "GUEST_005"
GUEST_ANALYSIS_LIMIT_EXCEEDED = "GUEST_006"
GUEST_UPLOAD_CREATE_ERROR = "GUEST_007"
GUEST_ANALYSIS_CREATE_ERROR = "GUEST_008"
GUEST_STATISTICS_ERROR = "GUEST_009"
GUEST_INVALID_SESSION_ID = "GUEST_010"
GUEST_UPLOAD_ERROR = "GUEST_011"
GUEST_UPLOADS_ERROR = "GUEST_012"
GUEST_ANALYSES_ERROR = "GUEST_013"
GUEST_SESSION_GET_ERROR = "GUEST_014"
GUEST_ANALYSIS_ERROR = "GUEST_015"

# ============================================
# Mã lỗi Profile (PROFILE)
# ============================================
PROFILE_NOT_FOUND = "PROFILE_001"
PROFILE_UPDATE_FAILED = "PROFILE_002"
PROFILE_INVALID_DATA = "PROFILE_003"
PROFILE_AVATAR_UPLOAD_FAILED = "PROFILE_004"
PROFILE_STATISTICS_ERROR = "PROFILE_005"
PROFILE_SEARCH_ERROR = "PROFILE_006"
PROFILE_COMPLETION_SUGGESTIONS_ERROR = "PROFILE_007"
PROFILE_GET_ERROR = "PROFILE_008"

# ============================================
# Mã lỗi Upload (UPLOAD)
# ============================================
UPLOAD_LOGS_RETRIEVAL_FAILED = "UPLOAD_001"
UPLOAD_LOGS_UNEXPECTED_ERROR = "UPLOAD_002"
UPLOAD_LOG_CREATE_ERROR = "UPLOAD_003"
UPLOAD_LOG_UPDATE_ERROR = "UPLOAD_004"
UPLOAD_LOG_NOT_FOUND = "UPLOAD_005"
UPLOAD_STATISTICS_ERROR = "UPLOAD_006"

# ============================================
# Mã lỗi hệ thống chung (System - SYS)
# ============================================
INTERNAL_ERROR = "SYS_001"
SYSTEM_ERROR = "SYS_002"
UNKNOWN_ERROR = "SYS_003"