# YOLO Detection Configuration
model:
  name: "yolov11"
  type: "detection"
  weights_path: "../detection/models/best_v2.pt"
  
inference:
  conf_threshold: 0.25
  iou_threshold: 0.45
  device: "cpu"
  
classes:
  - "wound"
  - "non_wound"
  
image:
  img_size: 640
